"""empty message

Revision ID: 55f6e2570a1d
Revises: 95304ea3d887
Create Date: 2022-03-02 16:41:51.087908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f6e2570a1d'
down_revision = '95304ea3d887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
