"""empty message

Revision ID: 95304ea3d887
Revises: 76d473747962
Create Date: 2022-03-02 16:28:43.644827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95304ea3d887'
down_revision = '76d473747962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
