"""empty message

Revision ID: a497183bcbc1
Revises: a66983c3cf5f
Create Date: 2022-02-25 21:42:58.948914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a497183bcbc1'
down_revision = 'a66983c3cf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('voted_at', sa.DATETIME(), nullable=True),
    sa.Column('vote', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
